apiVersion: cert-manager.io/v1beta1
kind: ClusterIssuer
metadata:
  name: lab-cluster-issuer
spec:
  acme:
    email: scott@brightwell.org
    privateKeySecretRef:
      name: acme-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        route53:
          accessKeyID: AKIARPBECU6BDYQHFLUI
          hostedZoneID: Z04408743JTEV2MFZLFYP # change for another DNS zone
          region: us-east-2
          secretAccessKeySecretRef:
            key: secret-access-key
            name: prod-route53-credentials-secret
    - http01:
        ingress:
          class: contour
