apiVersion: v1
data:
  secret-access-key: akh3TUlxTFl4aHU4SHFud04yRVFidjdRVVNJTHdUanFRV2tUUVlIdw==
kind: Secret
metadata:
  name: prod-route53-credentials-secret
  namespace: cert-manager
type: Opaque
