AVI_CA_DATA_B64: ""
AVI_CLOUD_NAME: ""
AVI_CONTROLLER: ""
AVI_DATA_NETWORK: ""
AVI_DATA_NETWORK_CIDR: ""
AVI_ENABLE: "false"
AVI_LABELS: ""
AVI_PASSWORD: ""
AVI_SERVICE_ENGINE_GROUP: ""
AVI_USERNAME: ""
CLUSTER_CIDR: 100.96.0.0/11
CLUSTER_NAME: tkg-mgmt
CLUSTER_PLAN: dev
ENABLE_CEIP_PARTICIPATION: "false"
ENABLE_MHC: "true"
IDENTITY_MANAGEMENT_TYPE: none
INFRASTRUCTURE_PROVIDER: vsphere
LDAP_BIND_DN: ""
LDAP_BIND_PASSWORD: ""
LDAP_GROUP_SEARCH_BASE_DN: ""
LDAP_GROUP_SEARCH_FILTER: ""
LDAP_GROUP_SEARCH_GROUP_ATTRIBUTE: ""
LDAP_GROUP_SEARCH_NAME_ATTRIBUTE: cn
LDAP_GROUP_SEARCH_USER_ATTRIBUTE: DN
LDAP_HOST: ""
LDAP_ROOT_CA_DATA_B64: ""
LDAP_USER_SEARCH_BASE_DN: ""
LDAP_USER_SEARCH_FILTER: ""
LDAP_USER_SEARCH_NAME_ATTRIBUTE: ""
LDAP_USER_SEARCH_USERNAME: userPrincipalName
OIDC_IDENTITY_PROVIDER_CLIENT_ID: ""
OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: ""
OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: ""
OIDC_IDENTITY_PROVIDER_ISSUER_URL: ""
OIDC_IDENTITY_PROVIDER_NAME: ""
OIDC_IDENTITY_PROVIDER_SCOPES: ""
OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: ""
SERVICE_CIDR: 100.64.0.0/13
TKG_HTTP_PROXY_ENABLED: "false"
TMC_REGISTRATION_URL: https://partnertanzuseamericas.tmc.cloud.vmware.com/installer?id=1ecadee07a49e9af486f2acb3e245a0de4fa77f5f1fde4b0afa4adfabdfff5ef&source=registration&type=tkgm
VSPHERE_CONTROL_PLANE_DISK_GIB: "40"
VSPHERE_CONTROL_PLANE_ENDPOINT: CHANGEME_ENDPOINT
VSPHERE_CONTROL_PLANE_MEM_MIB: "8192"
VSPHERE_CONTROL_PLANE_NUM_CPUS: "2"
VSPHERE_DATACENTER: /SDDC-Datacenter
VSPHERE_DATASTORE: /SDDC-Datacenter/datastore/WorkloadDatastore
VSPHERE_FOLDER: /SDDC-Datacenter/vm/Workloads/TKG
VSPHERE_NETWORK: tkg-network
VSPHERE_PASSWORD: <encoded:VHJELWozLWlMdzhTdllS>
VSPHERE_RESOURCE_POOL: /SDDC-Datacenter/host/Cluster-1/Resources/Compute-ResourcePool/TKG
VSPHERE_SERVER: 10.2.224.4
VSPHERE_SSH_AUTHORIZED_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4tGmW5PCQKz+JNio+Li6uWMQsYcG3WTCu50Vc2ctKrHqeL5WaApvGD0+dYgZiA7uZtSfbCrllVi9+322czlS0m78FVlKkTslh7J9e8ujl8x9QRkFPBCEOsFkDPlNjuMi9pFbtf9pQevSOr0pkK6Sdyx2MxnEz6Xf2EEAworMwdcfRD1lQyar5xntBc8TrNC6CYg5g8WOD9TBdHS409F+KE50iWxBR7PZ4DLt7A2S7SBxhmKrUaffNWGREfPSyl7DawzCsngHFMEuZiul06QHLAuhrK6/6r6OLmM7bV+OkpT/MNv5jfc+gXUAxf3lJexw8aZHTbt1J3pMmCBWjz1df root@tkg.vmware.corp
VSPHERE_TLS_THUMBPRINT: 93:D5:89:13:0F:E6:15:91:3C:71:79:BE:85:BA:D1:A1:03:6D:09:DD
VSPHERE_USERNAME: cloudadmin@vmc.local
VSPHERE_WORKER_DISK_GIB: "40"
VSPHERE_WORKER_MEM_MIB: "8192"
VSPHERE_WORKER_NUM_CPUS: "2"
